
Starting trainig
Not found pretrained weights. Continue without any pretrained weights.
Training Data Size : 50400
Validation Data Size : 5600
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:2952: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
epoch: 0    0 / 12600
lossD: 3.5177669525146484    lossG: 96.71460723876953 batch_time: 15.955827951431274s
L_adv: 2.821329116821289 L_id: 0.9798246026039124 L_attr: 4.037744998931885 L_rec: 0.4117853045463562
L_l2_eyes: 0.00846105720847845
L_landmarks: 0.003762325271964073
loss_adv_accumulated: 19.656426582336426
itertion :
Traceback (most recent call last):
  File "train.py", line 651, in <module>
    main(args)
  File "train.py", line 527, in main
    train(args, device=device)
  File "train.py", line 394, in train
    loss_adv_accumulated)
  File "train.py", line 256, in train_one_epoch
    res1 = get_faceswap('examples/images/training/source1.png', 'examples/images/training/target1.png', G, id_extractor, device)
  File "/workspace/utils/training/image_processing.py", line 107, in get_faceswap
    Yt, recon_src, recon_tgt = G(target, source, id_embedding)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/network/CrossU.py", line 72, in forward
    src_bottlneck_attr, src_z_attr1, src_z_attr2, src_z_attr3, src_z_attr4, src_z_attr5, src_z_attr6, src_z_attr7 = self.CUMAE_src(source)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/network/FFGenerator.py", line 260, in forward
    feat1 = self.conv1(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same